#!/usr/bin/env bash
# Writes docs/reference/commands.md from make help and docs/reference/presets.md from CMakePresets.json.
# With --check it writes nothing and fails when either page differs from what it would write.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
program="${0##*/}"

check=0
case "${1:-}" in
"") ;;
--check) check=1 ;;
-h | --help)
    echo "Usage: scripts/${program} [--check]"
    exit 0
    ;;
*)
    echo "${program}: unknown argument $1; see scripts/${program} --help" >&2
    exit 2
    ;;
esac

commands() {
    cat <<'HEADER'
# Commands

Generated by `scripts/gen-reference.sh` from `make help`; run `make docs` after changing the `Makefile`.
Set `PRESET`, `BASE`, or `FUZZ_SECONDS` on the command line, as in `make lint PRESET=asan`.

| Command | What it does |
| --- | --- |
HEADER
    # shellcheck disable=SC2016 # The backticks are Markdown, not a command substitution.
    make -C "${root}" --no-print-directory help |
        sed -n 's/^  \([A-Za-z0-9_.-]*\) *\(.*\)$/| `make \1` | \2 |/p'
}

presets() {
    cat <<'HEADER'
# Presets

Generated by `scripts/gen-reference.sh` from `CMakePresets.json`; run `make docs` after changing it.
Run every step of a preset with `cmake --workflow --preset <name>`. Builds go to `build/<configure preset>/`.

HEADER
    python3 - "${root}/CMakePresets.json" <<'PYTHON'
import json
import sys

presets = json.load(open(sys.argv[1]))
kinds = ["configure", "build", "test", "workflow"]
by_kind = {kind: {p["name"]: p for p in presets.get(kind + "Presets", [])} for kind in kinds}


def inherits_gcc(name):
    preset = by_kind["configure"].get(name)
    if preset is None:
        return False
    parents = preset.get("inherits", [])
    parents = [parents] if isinstance(parents, str) else parents
    return name == "gcc" or any(inherits_gcc(parent) for parent in parents)


names = []
for kind in kinds:
    for name, preset in by_kind[kind].items():
        if not preset.get("hidden") and name not in names:
            names.append(name)

print("| Preset | What it builds or runs | Configure | Build | Test | Workflow | Listed on |")
print("| --- | --- | --- | --- | --- | --- | --- |")
for name in names:
    test = by_kind["test"].get(name, {})
    configure = name if name in by_kind["configure"] else test.get("configurePreset", name)
    description = by_kind["configure"].get(name, {}).get("displayName") or test.get("displayName", "")
    marks = ["yes" if name in by_kind[kind] else "no" for kind in kinds]
    hosts = "Linux" if inherits_gcc(configure) else "Linux, macOS"
    print(f"| `{name}` | {description} | " + " | ".join(marks) + f" | {hosts} |")
PYTHON
}

status=0
for page in commands presets; do
    target="${root}/docs/reference/${page}.md"
    if [ "${page}" = commands ]; then content="$(commands)"; else content="$(presets)"; fi
    if [ "${check}" -eq 1 ]; then
        if ! diff -u "${target}" - <<<"${content}" >&2; then
            echo "${program}: docs/reference/${page}.md is out of date; run make docs" >&2
            status=1
        fi
    else
        printf '%s\n' "${content}" >"${target}"
    fi
done
exit "${status}"
