#!/usr/bin/env bash
# Scaffolds apps/<name>/ as an executable that links myproj::core and prints the version.
# The next configure picks it up; the binary lands in build/<preset>/bin/<name>.
set -euo pipefail

# shellcheck source-path=SCRIPTDIR source=lib/scaffold.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib/scaffold.sh"

if [ "$#" -ne 1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    cat <<USAGE
Usage: scripts/new-app.sh <name>

Creates apps/<name>/ with an executable target <name> that links myproj::core.
USAGE
    if [ "$#" -eq 1 ]; then exit 0; fi
    exit 2
fi

name="$1"
validate_name "${name}"
refuse_existing "apps/${name}"
refuse_taken_targets "${name}"

write_file "apps/${name}/CMakeLists.txt" <<CMAKE
# The ${name} app: executable ${name} in build/<preset>/bin/.
# Generated by scripts/new-app.sh; add every module the app uses to DEPS.
project_add_app(NAME ${name} DEPS myproj::core)
CMAKE

write_file "apps/${name}/main.cpp" <<CPP
// Entry point of the ${name} app.
// Generated by scripts/new-app.sh; replace the body with the app's work.
#include <myproj/version.hpp>

#include <print>

int main() {
    std::println("${name} {}", myproj::version_string);
    return 0;
}
CPP
