#!/usr/bin/env bash
# Scaffolds libs/<name>/ as a compiled module with a namespace stub and one passing unit test.
# The next configure picks it up; nothing else needs editing.
set -euo pipefail

# shellcheck source-path=SCRIPTDIR source=lib/scaffold.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib/scaffold.sh"

if [ "$#" -ne 1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    cat <<USAGE
Usage: scripts/new-module.sh <name>

Creates libs/<name>/ with target myproj::<name> in namespace myproj::<name>,
and tests/unit/<name>/ with one passing test labeled <name>.
USAGE
    if [ "$#" -eq 1 ]; then exit 0; fi
    exit 2
fi

name="$1"
validate_name "${name}"
refuse_existing "libs/${name}" "tests/unit/${name}"
refuse_taken_targets "myproj_${name}" "${name}_unit_tests"
suite="$(camel_case "${name}")"

write_file "libs/${name}/CMakeLists.txt" <<CMAKE
# The ${name} module: target myproj_${name}, alias myproj::${name}.
# Generated by scripts/new-module.sh; add PUBLIC_DEPS or PRIVATE_DEPS as the module grows.
project_add_module(NAME ${name})
CMAKE

write_file "libs/${name}/include/${name}/${name}.hpp" <<CPP
// Public interface of the ${name} module.
// Generated by scripts/new-module.sh; replace the stub with the module's API.
#pragma once

#include <string_view>

namespace myproj::${name} {

// Returns the module name; a stub that proves the module builds, links, and tests.
[[nodiscard]] std::string_view module_name() noexcept;

} // namespace myproj::${name}
CPP

write_file "libs/${name}/src/${name}.cpp" <<CPP
// Implementation of the ${name} module.
// Generated by scripts/new-module.sh; delete src/ to make the module header-only.
#include "${name}/${name}.hpp"

namespace myproj::${name} {

std::string_view module_name() noexcept {
    return "${name}";
}

} // namespace myproj::${name}
CPP

write_file "tests/unit/${name}/test_${name}.cpp" <<CPP
// Unit tests of the ${name} module, run with: ctest --preset dev -L ${name}
// Generated by scripts/new-module.sh; replace the stub test with real ones.
#include <gtest/gtest.h>

#include "${name}/${name}.hpp"

namespace myproj::${name} {

TEST(${suite}, ModuleNameIsTheDirectoryName) {
    EXPECT_EQ(module_name(), "${name}");
}

} // namespace myproj::${name}
CPP
