set(TEMPLATE_PROJECT_NAME
    "DummyProject"
    CACHE STRING "Project name used to derive template target and package names"
)

if(NOT TEMPLATE_PROJECT_NAME MATCHES "^[A-Za-z][A-Za-z0-9_]*$")
  message(FATAL_ERROR "TEMPLATE_PROJECT_NAME must be a CMake-friendly identifier")
endif()

string(TOLOWER "${TEMPLATE_PROJECT_NAME}" TEMPLATE_PROJECT_NAME_LOWER)

set(TEMPLATE_LIBRARY_TARGET "${TEMPLATE_PROJECT_NAME}")
set(TEMPLATE_NAMESPACE "${TEMPLATE_PROJECT_NAME}")
set(TEMPLATE_NAMESPACED_TARGET "${TEMPLATE_NAMESPACE}::${TEMPLATE_LIBRARY_TARGET}")
set(TEMPLATE_TEST_PROJECT "${TEMPLATE_PROJECT_NAME}Tests")
set(TEMPLATE_TEST_TARGET "${TEMPLATE_PROJECT_NAME}Tests")
set(TEMPLATE_BENCHMARK_TARGET "${TEMPLATE_PROJECT_NAME}Benchmarks")
set(TEMPLATE_STANDALONE_PROJECT "${TEMPLATE_PROJECT_NAME}Standalone")
set(TEMPLATE_STANDALONE_TARGET "${TEMPLATE_PROJECT_NAME_LOWER}_standalone")
set(TEMPLATE_BINARY_DIR_NAME "${TEMPLATE_PROJECT_NAME}")
