name: Comprehensive Checks

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  quality-checks:
    uses: ./.github/workflows/quality-checks.yaml

  safety-checks:
    uses: ./.github/workflows/safety-checks.yaml

  coverage-checks:
    uses: ./.github/workflows/coverage-checks.yaml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  performance-checks:
    uses: ./.github/workflows/performance-checks.yaml
