name: MacOS

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
      - name: Install dependencies
        run: brew install libomp tbb
      - name: Configure
        run: cmake -Stest -Bbuild -DCMAKE_BUILD_TYPE=Release -DUSE_SANITIZER='Thread;Undefined' -DCMAKE_CXX_FLAGS="-march=native -mtune=native"
      - name: Build
        run: cmake --build build -j$(sysctl -n hw.logicalcpu)
      - name: Test
        run: cd build && ctest --build-config Release
      - name: Collect code coverage
        run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
