name: Quality Checks

on:
  workflow_call:

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libtbb-dev llvm clang-tools cmake

      # Add CPM cache
      - name: Cache CPM Dependencies
        uses: actions/cache@v3
        with:
          path: "**/cpm_modules"
          key: cpm-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      # Configure first to generate compile_commands.json
      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_FLAGS="-march=native -mtune=native"

      - name: clang-tidy review
        uses: ZedThree/clang-tidy-review@v0.19.0
        if: github.event_name == 'pull_request'
        with:
          build_dir: build
          config_file: .clang-tidy
          exclude: "external/**"
          cmake_command: "" # Empty because we already configured CMake

      - name: Run clang-tidy directly
        if: github.event_name == 'push'
        run: |
          run-clang-tidy -p build
