name: Standalone

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache CPM Dependencies
        uses: actions/cache@v3
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Configure
        run: |
          cmake -S . -B build/standalone \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_FLAGS="-march=native -mtune=native"

      - name: Build
        run: cmake --build build/standalone -j$(nproc)

      - name: Get Project Name
        id: get_name
        run: |
          echo "PROJECT_NAME=$(cmake -L -N -B build/standalone | grep 'PROJECT_NAME' | cut -d'=' -f2)" >> $GITHUB_OUTPUT

      - name: Run
        working-directory: build/standalone
        run: |
          echo "Executable name: ${{ steps.get_name.outputs.PROJECT_NAME }}"
          ls -la
          ./${{ steps.get_name.outputs.PROJECT_NAME }}
